SELECT 
    MB.NAME,
    BT.BORROW_DATE,
    BT.ESTIMATE_RETURN_DATE,
    DATEDIFF(DAY, BT.BORROW_DATE, BT.ESTIMATE_RETURN_DATE) AS Total_Day,
    BT.TOTAL_RENT_AMOUNT,
    STRING_AGG(
        CONCAT(
            ROW_NUMBER() OVER (PARTITION BY BT.CODE ORDER BY BTD.BOOK_CODE) AS No,
            ': ', MBK.BOOK_TITLE, ' ', MBK.AUTHOR, ' ', MBK.PUBLISHER, ' ',
            BTD.QUANTITY, ' ', BTD.RENT_AMOUNT, ' ', (BTD.QUANTITY * BTD.RENT_AMOUNT)
        ), '; '
    ) AS Borrowing_Book_List
FROM 
    BORROW_TRANSACTION BT
JOIN 
    MASTER_BORROWER MB ON BT.BORROWER_CODE = MB.CODE
JOIN 
    BORROW_TRANSACTION_DETAIL BTD ON BT.CODE = BTD.BORROW_CODE
JOIN 
    MASTER_BOOK MBK ON BTD.BOOK_CODE = MBK.BOOK_CODE
GROUP BY 
    MB.NAME, BT.BORROW_DATE, BT.ESTIMATE_RETURN_DATE, BT.TOTAL_RENT_AMOUNT, BT.CODE;

----------------------------------------------------------------------
SELECT 
    MB.NAME,
    BT.BORROW_DATE,
    BT.ESTIMATE_RETURN_DATE,
    DATEDIFF(DAY, BT.BORROW_DATE, BT.ESTIMATE_RETURN_DATE) AS Total_Day,
    BT.TOTAL_RENT_AMOUNT,
    MBK.BOOK_TITLE,
    MBK.AUTHOR,
    MBK.PUBLISHER,
    BTD.QUANTITY,
    BTD.RENT_AMOUNT
FROM 
    BORROW_TRANSACTION BT
JOIN 
    MASTER_BORROWER MB ON BT.BORROWER_CODE = MB.CODE
JOIN 
    BORROW_TRANSACTION_DETAIL BTD ON BT.CODE = BTD.BORROW_CODE
JOIN 
    MASTER_BOOK MBK ON BTD.BOOK_CODE = MBK.BOOK_CODE
WHERE
    BT.CODE = @p_borrow_code
