select * from [dbo].[MASTER_TRAINEE_RESULT_TRANSACTION]
select * from [dbo].[MASTER_TRAINEE_RESULT_TRANSACTION_MATERI]
select * from [dbo].[MASTER_TRAINEE_RESULT_TRANSACTION_MATERI_DETAIL]


select FORMAT(mtrt.START_TRAINEE_DATE, 'dd/MM/yyyy') from MASTER_TRAINEE_RESULT_TRANSACTION mtrt
