BEGIN TRANSACTION 
--SELECT * FROM dbo.WORK_ORDER

--SELECT * FROM PAYMENT_REQUEST

SELECT pr.PAYMENT_SOURCE_NO, COUNT(pr.PAYMENT_SOURCE_NO) AS total_count FROM dbo.PAYMENT_REQUEST pr
where pr.PAYMENT_STATUS = 'POST'
GROUP BY pr.PAYMENT_SOURCE_NO
HAVING COUNT(pr.PAYMENT_SOURCE_NO) > 1

--SELECT PAYMENT_REQUEST_CODE, count(PAYMENT_REQUEST_CODE) as total_count2 FROM dbo.PAYMENT_TRANSACTION_DETAIL
--GROUP BY PAYMENT_REQUEST_CODE
--HAVING COUNT(PAYMENT_REQUEST_CODE) > 1

--SELECT  count(code) as total_count3 FROM dbo.ASSET
--GROUP BY code
--HAVING COUNT(code) > 1

--SELECT count(ASSET_CODE) as total_count4 FROM dbo.ASSET_VEHICLE
--GROUP BY ASSET_CODE
--HAVING COUNT(ASSET_CODE) > 1

ROLLBACK TRANSACTION 
